name: InfraPatch Github Action
description: Subaction working as wrapper for infrapatch cli
author: "Noah Canadea"
inputs:
  target_branch:
    description: "Target branch to create a pull request against"
    required: true
  github_token:
    description: "GitHub access token. Defaults to github.token."
    required: true
  command:
    description: "The CLI Command to run, can be either report or update. Defaults to update"
    required: true
  patch_branch_name:
    description: "Name of the branch where changes will be pushed to. Defaults to feature/infra-patch"
    required: true
  registry_secrets:
    description: "Registry secrets to use for private registries"
    required: true
runs:
  using: node20
  main: index.js
