name: "Check Format and Lint Code"

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: true

jobs:
  check_code:
    name: "Check Format and Lint Code"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ inputs.python_version }}

      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

      - name: Check code format with ruff
        run: ruff format --check .

      - name: Check code with ruff
        run: ruff check .






