name: "Check Format and Lint Code"

on:
  workflow_call:

jobs:
  check_code:
    name: "Check Format and Lint Code"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Python Version
        id: get_python_verion
        run: |
          python_version=$(cat python_version.txt)
          echo "Using Python version $python_version"
          echo "::set-output name=python_version::$(echo $python_version)"
        
      - name: Install Python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ steps.get_python_verion.outputs.python_version }}

      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

      - name: Check code format with ruff
        run: ruff format --check .

      - name: Check code with ruff
        run: ruff check .






