name: "Run Python Unit Tests"


on:
  workflow_call:

jobs:
  integration-test:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Python Version
        id: get_python_verion
        run: |
          python_version=$(cat python_version.txt)
          echo "Using Python version $python_version"
          echo "::set-output name=python_version::$(echo $python_version)"

      - name: Install Python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ steps.get_python_verion.outputs.python_version }}

      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

      - name: Set timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'Europe/Berlin'

      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
            verbose: true
            emoji: true
            job-summary: true
            click-to-expand: true
            report-title: 'InfraPatch Unit-Tests Report'







